Pull request for project review
leonmezu1/Rails-Private-Events pull request #1
Opened 2020-03-16 21:53 UTC by leonmezu1

# Project requirements:

 - [x]  Build a Rails application ensuring that:
    - The models, associations, controllers, and views are working as expected
    - Sign-up, log-in and log-out methods within the app sessions behavior work successfully
    - Models' special associations and scopes work properly
    - Users can create, view, edit and destroy events
    - Users can assist events

Further information is available at [The Odin Project Associations](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)

2020-03-18 22:07 UTC, Usagib commented
PR for code review: Lint errors fixed

2020-03-19 19:57 UTC, mosaaleb requested changes
### Well done Team :clap:

The projects looks really nice, most requirements are handled, there is only two minor requirements to handle before moving on. Please take a look at my comments below.


#### Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-03-19 19:57 UTC, mosaaleb commented on app/views/events/show.html.erb
> +      <% end %>
- [ ] The event's show page displays the list of attendants

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png)

2020-03-19 19:57 UTC, mosaaleb commented on app/views/events/show.html.erb
> +      <% if @event.upcoming? %>
- [ ] There shoud be absolutely NO logic in views.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png)

Please move the logic to helpers.

2020-03-23 17:04 UTC, leonmezu1 commented
Required changes completed

2020-03-23 17:47 UTC, nikasulo approved these changes
# Great work! @leonmezu1 and @Usagib :medal_military: 
Please merge and keep moving forward! Great job! I wish you the very best and see you at the very top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-03-23 20:10 UTC, merged